#!/usr/bin/env bash
# setup.sh -- seeds /labs/08-streams-and-redirection/03-heredocs
#
# THE ANSWER KEY. Students are told not to open this.
#
# Teaching goal: a here-document is a redirection of fd 0 from text the shell
# holds, not from a file. Two decisions matter and both bite:
#   1. QUOTED vs UNQUOTED delimiter. <<EOF expands $var, `cmd`, \ escapes.
#      <<'EOF' does not. Every "why did my script eat the dollar signs" bug is
#      this one decision.
#   2. <<- strips LEADING TABS ONLY. Not spaces. This is the single most
#      commonly misremembered fact in the shell, so the lab ships one file
#      indented with tabs and one with spaces and lets the student measure.
#
# Also here: <<< herestrings, and the fact that a heredoc is stdin, so it
# composes with everything that reads stdin.
#
# THE BROKEN SCRIPT: bin/mkbanner uses an unquoted delimiter and its output is
# missing the literal $ fields. bin/mkbanner-fixed is the same script with one
# character changed. Exercise 28 asks which character.
#
# Measured facts used by the exercises:
#   templates/banner.txt     4 lines, contains $DECK $SHIFT literally
#   templates/tabbed.txt     4 lines, indented with TABS
#   templates/spaced.txt     4 lines, indented with SPACES (identical text)
#   data/decks.txt           4 lines
#
# Idempotent: removes its own tree first, creates nothing outside LAB.
set -euo pipefail

LAB="/labs/08-streams-and-redirection/03-heredocs"
rm -rf "$LAB"
mkdir -p "$LAB"/{bin,data,templates,notes,scratch}
cd "$LAB"

########## programs ##########

cat > bin/mkbanner <<'OUTER'
#!/usr/bin/env bash
# mkbanner -- prints the deck 05 shift banner.
# Something is wrong with it and has been for a while.
DECK=05
SHIFT=beta
cat <<EOF
==========================================
 deck $DECK -- shift $SHIFT
 template fields: $DECK_NAME and $SHIFT_LEAD
 generated by: $(id -un)
==========================================
EOF
OUTER

cat > bin/mkbanner-fixed <<'OUTER'
#!/usr/bin/env bash
# mkbanner-fixed -- the same script, one character different.
DECK=05
SHIFT=beta
cat <<'EOF'
==========================================
 deck $DECK -- shift $SHIFT
 template fields: $DECK_NAME and $SHIFT_LEAD
 generated by: $(id -un)
==========================================
EOF
OUTER

cat > bin/seedform <<'OUTER'
#!/usr/bin/env bash
# seedform -- writes a blank station form to stdout. Two arguments: form, deck.
form=${1:?usage: seedform FORM DECK}
deck=${2:?usage: seedform FORM DECK}
cat <<EOF
form $form -- deck $deck
  raised .......
  by ...........
  f1=
  f2=
EOF
OUTER

chmod 755 bin/mkbanner bin/mkbanner-fixed bin/seedform

########## templates ##########

cat > templates/banner.txt <<'OUTER'
==========================================
 deck $DECK -- shift $SHIFT
 fields: $DECK_NAME and $SHIFT_LEAD
==========================================
OUTER

# tabs, written with printf so nothing can silently convert them
printf '\tdeck 05 checklist\n\t  1. walk the bank\n\t  2. read the panel\n\t  3. sign the board\n' \
  > templates/tabbed.txt
printf '    deck 05 checklist\n      1. walk the bank\n      2. read the panel\n      3. sign the board\n' \
  > templates/spaced.txt

########## data ##########

printf 'deck 03\ndeck 05\ndeck 07\ndeck 11\n' > data/decks.txt
printf 'p-a 41\np-b 40\np-c 44\np-d 39\np-e 40\np-f 43\n' > data/readings.txt

########## notes ##########

cat > notes/heredoc.txt <<'OUTER'
Here-documents
--------------

A here-document is a redirection of fd 0. The text does not live in a file --
the shell holds it and hands it to the command as standard input.

  cmd <<EOF
  ...lines...
  EOF

The delimiter is any word you like. EOF is a convention, not a keyword. The
closing line must contain the delimiter and nothing else, at the start of the
line, with no trailing spaces. A trailing space is the classic cause of
"unexpected end of file".

THE ONE DECISION THAT MATTERS

  <<EOF     the body is expanded: $var, ${var}, $(cmd), `cmd`, \ escapes
  <<'EOF'   the body is literal: every character survives, nothing runs
  <<"EOF"   same as quoted. Any quoting of the delimiter turns expansion off.

Quote the delimiter unless you actually want expansion. A body that contains
shell syntax -- a script, a config file, an awk program, a password, anything
with a $ in it -- must be quoted or the shell will help you.

INDENTATION

  <<-EOF    strips leading TABS from every body line and from the delimiter

TABS ONLY. Not spaces. An editor set to "insert spaces" makes <<- do nothing
at all, silently, and the body keeps its indentation. This is why so many
scripts have a heredoc jammed against the left margin in the middle of an
indented block: somebody gave up.

HERESTRINGS

  cmd <<<"one line of text"

Same idea, one line, and the same quoting rules. `<<<` adds a trailing
newline. It is the shortest way to feed a string to something that insists on
reading stdin:

  grep -c deck <<<"$text"
  read -r a b <<<"05 beta"

WHAT A HEREDOC IS NOT

It is not a string literal and it is not a file. It is fd 0. So it composes:
anything that reads stdin can be fed one, including things you would not think
of -- `wc`, `sort`, `sed`, `bash` itself.
OUTER

cat > notes/page.txt <<'OUTER'
From: cass
To: deck 05

The shift banner has been printing the field names instead of the field values
for as long as I have been here, and today somebody asked me why. I said I
would find out. There are two copies of the script in bin/ and I cannot see any
difference between them, which is the most annoying possible outcome.
OUTER

printf 'Yours.\n' > scratch/README

find . -exec touch -h -d '2187-06-14 08:00:00' {} +
touch -d '2186-04-02 11:20:00' bin/mkbanner

echo "seeded $LAB"
