#!/usr/bin/env bash
# Seeds 11/06 -- Incident 10. Trace 11.
#
# The trace: a line in a startup file, sourced three levels down, that removes
# exactly one directory from one account's view of the station archive. The
# file it hides is the chapter 2 archive. Nothing is deleted, nothing is
# chmodded, nothing is renamed. The directory is there for everyone whose shell
# has not been taught not to see it.
#
# Mechanism (measured before writing):
#   GLOBIGNORE with a pattern makes matching names vanish from ALL globbing --
#     echo */, ls *, tab completion -- and it also silently switches dotglob on
#   an `alias ls='ls --hide=...'` hides it from a bare `ls` as well, so the two
#     mechanisms cover each other and finding one is not finding both
#   both live in ~/.config/kestrel/env.sh, sourced by .bashrc, sourced by
#     .profile -- so `grep GLOBIGNORE ~/.bashrc` finds nothing
#   `find`, `echo` with a quoted name, and `ls -d name` all still see it: the
#     directory is not hidden, the shell is
#
# Four stages. Stage tokens are STAGE{...} and are NOT registered as flags.
set -euo pipefail

LAB="/labs/11-environment-and-config/06-incident-10"

rm -rf "$LAB"
mkdir -p "$LAB"/{bin,notes,scratch}
mkdir -p "$LAB"/homes/dorn/.config/kestrel
mkdir -p "$LAB"/archive/{01-boarding,02-navigation,03-files,04-creating,05-globbing}

# --- the archive: five ordinary directories, one of which is a problem -------
cat > "$LAB/archive/01-boarding/README" <<'EOF'
Station archive, section 01. Boarding procedure, induction, deck assignment.
EOF
cat > "$LAB/archive/02-navigation/README" <<'EOF'
Station archive, section 02. Filesystem layout, absolute and relative paths,
and the deck-to-path mapping used by every tool on this station.
EOF
cat > "$LAB/archive/02-navigation/deck-map.txt" <<'EOF'
    deck 02 path map -- station archive, section 02
    ---------------------------------------------------------------

    This is the file the automated tools read when they translate a deck
    number into a path. Every audit on this station depends on it and no audit
    on this station reports whether it could read it.

    deck-01  /var/kestrel/decks/01
    deck-02  /var/kestrel/decks/02
    deck-03  /var/kestrel/decks/03
    deck-04  /var/kestrel/decks/04
    deck-05  /var/kestrel/decks/05
EOF
cat > "$LAB/archive/03-files/README" <<'EOF'
Station archive, section 03. File types, links, and what `file` actually reads.
EOF
cat > "$LAB/archive/04-creating/README" <<'EOF'
Station archive, section 04. Creating, copying and destroying, and the three
ways to lose a file while believing you moved it.
EOF
cat > "$LAB/archive/05-globbing/README" <<'EOF'
Station archive, section 05. Globbing and quoting. The shell expands the
pattern. The program never sees it. Remember this in about ten minutes.
EOF

# --- the account -------------------------------------------------------------
cat > "$LAB/homes/dorn/.profile" <<'EOF'
# ~/.profile -- read by login shells.

if [ -n "$BASH_VERSION" ] && [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi

export STATION_ROLE=engineer
export ARCHIVE=/labs/11-environment-and-config/06-incident-10/archive
EOF

cat > "$LAB/homes/dorn/.bashrc" <<'EOF'
# ~/.bashrc -- interactive settings.

alias ll='ls -l'
alias la='ls -la'
alias ..='cd ..'

HISTCONTROL=ignoreboth
HISTSIZE=2000
shopt -s histappend
shopt -s checkwinsize

# Station-supplied environment. Do not edit; regenerated by the toolchain.
if [ -f "$HOME/.config/kestrel/env.sh" ]; then
    . "$HOME/.config/kestrel/env.sh"
fi

PS1='\u@\h:\w\$ '
EOF

cat > "$LAB/homes/dorn/.config/kestrel/env.sh" <<'EOF'
# Station toolchain environment. Generated 2186-03-02. Regenerated on upgrade.

export TOOLCHAIN=/opt/kestrel/toolchain
export EDITOR=nano
export LESS='-R'

# Suppress archive sections retired by the 2186 reorganisation.
GLOBIGNORE='02-navigation:02-navigation/'
alias ls='ls --hide=02-navigation'
EOF

cat > "$LAB/homes/dorn/.bash_logout" <<'EOF'
# ~/.bash_logout
EOF

# --- notes -------------------------------------------------------------------
cat > "$LAB/notes/incident.txt" <<'EOF'
    INCIDENT 10 -- two people, one directory, two answers
    ---------------------------------------------------------------

    An engineer reports that the station archive is missing a section. Another
    engineer, standing at the same terminal, in the same directory, running the
    same command, says it is there.

    Both of them are telling the truth.

    Nothing has been deleted. Every file in the archive is present, readable,
    and unmodified -- you can check that before you start and you should.
    What differs is the shell, and a shell is configured per account.

    The account whose view is wrong is `homes/dorn`. You do not have to log in
    as anyone: you have HOME, and lesson 03 taught you what a login shell does
    with it.

        HOME=$PWD/homes/dorn bash -l

    That is a login shell reading that account's startup files, running as you,
    in a directory you can leave whenever you like. Type `exit` to get out.

    Four checkpoints. Each one prints a STAGE{...} token when you have actually
    done the thing; each one tells you loudly when you have not. Stage tokens
    are not flags and `kestrel flags submit` will reject them.
EOF

cat > "$LAB/notes/rules.txt" <<'EOF'
    Rules of repair
    ---------------------------------------------------------------

    1. Do not delete `.config/kestrel/env.sh`.
    2. Do not delete, comment out or edit the two lines inside it that cause
       the problem. The checker takes a checksum of that file and will refuse
       a repair that changed it.
    3. Do not chmod anything, and do not move the archive.

    This is not a puzzle constraint. A deleted line explains nothing. The next
    upgrade regenerates that file -- it says so in its own first comment -- and
    an account that was repaired by deletion breaks again silently. You are
    going to fix it the way the shell itself decides things, which is the
    subject of the whole chapter.

    You are allowed, and expected, to edit `.bashrc`.
EOF

cat > "$LAB/notes/page.txt" <<'EOF'
    cass -- 2187-06-28 06:15

    I am not asking you to fix anything. I am asking you to tell me the machine
    is broken, because I ran `ls` and got five sections, and the engineer next
    to me ran `ls` and got four, and we did it three times, and once we swapped
    chairs.

    I checked whether either of us had a typo. We did not.
    I checked whether the directory had been deleted between runs. It had not.
    I have run out of things I know how to check.

    If the answer turns out to be that a computer can show two people different
    contents of the same directory and both of them are correct, I would like
    that in writing, because I do not currently believe it.
EOF

cat > "$LAB/notes/toolchain.txt" <<'EOF'
    Station toolchain -- account environment files
    ---------------------------------------------------------------

    Each account carries a generated environment file at

        ~/.config/kestrel/env.sh

    It is sourced by the account's ~/.bashrc, which is sourced by ~/.profile.
    It is regenerated on toolchain upgrade and local edits to it are lost.

    Generated files are owned by the account, not by the toolchain. The
    toolchain writes them; it does not audit them afterwards, and it has never
    compared one account's file against another's.
EOF

cat > "$LAB/scratch/README" <<'EOF'
Yours. Copy things here before you experiment on them.
EOF

# --- stage 1: name the section that disappears ------------------------------
cat > "$LAB/bin/compare-view" <<'EOF'
#!/usr/bin/env bash
# Checkpoint 1. Usage: compare-view <section-directory-name>
#
# Name the archive section that one account cannot see and everyone else can.
set -uo pipefail

LAB="/labs/11-environment-and-config/06-incident-10"
want="02-navigation"

if [ $# -ne 1 ]; then
    echo "compare-view: give me exactly one section name." >&2
    echo "usage: compare-view <section-directory-name>" >&2
    exit 2
fi

if [ ! -d "$LAB/archive/$1" ]; then
    echo "REJECTED: '$1' is not a section of this archive." >&2
    echo "          There are five. Two shells disagree about how many." >&2
    exit 1
fi

if [ "$1" != "$want" ]; then
    echo "REJECTED: '$1' is visible in both shells. Compare them again." >&2
    echo "          Run the same command in your shell and in a login shell" >&2
    echo "          with HOME set to the account, and diff the two lists." >&2
    exit 1
fi

echo "STAGE{one-directory-two-answers}"
EOF
chmod 755 "$LAB/bin/compare-view"

# --- stage 2: name the mechanism and the file it lives in -------------------
cat > "$LAB/bin/name-mechanism" <<'EOF'
#!/usr/bin/env bash
# Checkpoint 2. Usage: name-mechanism <VARIABLE> <path-to-file>
#
# Two things hide that directory and they are not the same thing. Name the
# shell VARIABLE that hides it from globbing, and the file both of them live
# in, as a path relative to the account's home directory.
set -uo pipefail

if [ $# -ne 2 ]; then
    echo "name-mechanism: two arguments." >&2
    echo "usage: name-mechanism <VARIABLE> <path-relative-to-home>" >&2
    exit 2
fi

var=$1
file=${2#./}
file=${file#\~/}

case "$var" in
    GLOBIGNORE) ;;
    LS_COLORS|GLOBIGNORECASE|HIDE|IGNOREEOF|FIGNORE)
        echo "REJECTED: '$var' is a real variable and it is not this one." >&2
        echo "          The one you want removes names from a glob's result." >&2
        exit 1 ;;
    *)
        echo "REJECTED: '$var' is not what is hiding it from '*'." >&2
        echo "          A shell variable is doing it. Read the account's" >&2
        echo "          startup files all the way down -- .profile sources" >&2
        echo "          something, which sources something else." >&2
        exit 1 ;;
esac

case "$file" in
    .config/kestrel/env.sh) ;;
    .bashrc|.profile|.bash_profile)
        echo "REJECTED: the account does read '$file', but the line is not in" >&2
        echo "          it. Follow what that file sources." >&2
        exit 1 ;;
    *)
        echo "REJECTED: '$file' is not where it is written." >&2
        exit 1 ;;
esac

echo "STAGE{two-mechanisms-one-file}"
EOF
chmod 755 "$LAB/bin/name-mechanism"

# --- stage 3: repair, without touching the generated file -------------------
cat > "$LAB/bin/verify-repair" <<'EOF'
#!/usr/bin/env bash
# Checkpoint 3. Usage: verify-repair
#
# Checks three things:
#   1. .config/kestrel/env.sh is byte-for-byte what the toolchain generated
#   2. a fresh LOGIN shell for that account sees all five archive sections
#      when it globs
#   3. that same shell's `ls` shows all five too
set -uo pipefail

LAB="/labs/11-environment-and-config/06-incident-10"
HOMEDIR="$LAB/homes/dorn"
GENERATED="423edca9f8d10d158b52dbb51727c871"

fail() { echo "REJECTED: $*" >&2; exit 1; }

[ -f "$HOMEDIR/.config/kestrel/env.sh" ] \
    || fail "the generated file is gone. That is not a repair. kestrel reset 11/06"

got=$(md5sum < "$HOMEDIR/.config/kestrel/env.sh" | cut -d' ' -f1)
[ "$got" = "$GENERATED" ] \
    || fail "the generated file has been edited. Put it back (kestrel reset 11/06 if you must) and fix this somewhere the toolchain will not overwrite."

glob=$(printf '%s\n' 'cd "$ARCHIVE" || exit 1' 'echo */' \
       | env -i HOME="$HOMEDIR" PATH=/usr/local/bin:/usr/bin:/bin TERM=dumb bash -l 2>/dev/null)
case "$glob" in
    *02-navigation*) ;;
    "") fail "a fresh login shell for that account could not even reach the archive. Did ARCHIVE survive your edit?" ;;
    *)  fail "a fresh login shell still cannot glob 02-navigation. It saw: $glob" ;;
esac

# The alias must be expanded on a LATER line than the shopt -- 11/04's rule.
lsout=$(printf '%s\n' 'shopt -s expand_aliases' 'cd "$ARCHIVE" || exit 1' 'ls' \
        | env -i HOME="$HOMEDIR" PATH=/usr/local/bin:/usr/bin:/bin TERM=dumb bash -l 2>/dev/null)
case "$lsout" in
    *02-navigation*) ;;
    *) fail "globbing is fixed but a bare \`ls\` still hides it. There were two mechanisms. You have dealt with one." ;;
esac

echo "STAGE{last-line-wins}"
echo
echo "Repair verified. The generated file is untouched and the account sees"
echo "the whole archive. Checkpoint 4: bin/incident-close"
EOF
chmod 755 "$LAB/bin/verify-repair"

# --- stage 4: the flag ------------------------------------------------------
cat > "$LAB/bin/incident-close" <<'EOF'
#!/usr/bin/env bash
# Checkpoint 4. Usage: incident-close <stage-3-token> <date-the-line-was-written>
#
# The report needs two things: proof you repaired it, and the date the hiding
# was written. The second is not in any note. It is a property of the file,
# and chapter 03 told you which command reads it. Format: YYYY-MM-DD
set -uo pipefail

LAB="/labs/11-environment-and-config/06-incident-10"
FILE="$LAB/homes/dorn/.config/kestrel/env.sh"

if [ $# -ne 2 ]; then
    echo "incident-close: two arguments." >&2
    echo "usage: incident-close <stage-3-token> <YYYY-MM-DD>" >&2
    exit 2
fi

if [ "$1" != "STAGE{last-line-wins}" ]; then
    echo "REJECTED: that is not the checkpoint 3 token." >&2
    echo "          Run bin/verify-repair and pass what it prints." >&2
    exit 1
fi

want=$(stat -c '%y' "$FILE" | cut -d' ' -f1)
if [ "$2" != "$want" ]; then
    echo "REJECTED: '$2' is not when that file was last written." >&2
    echo "          Read it off the file itself, not off a comment inside it." >&2
    echo "          A comment is a claim. A timestamp is a record." >&2
    exit 1
fi

# The report, including the flag, is not stored here in plain text --
# `grep -r KESTREL` should not close an incident for you.
base64 -d <<'REPORT'
CklOQ0lERU5UIDEwIC0tIENMT1NFRAoKICAgIFJlcG9ydGVkIGFzOiBhIGRpcmVjdG9yeSBt
aXNzaW5nIGZyb20gdGhlIHN0YXRpb24gYXJjaGl2ZS4KICAgIEFjdHVhbGx5OiAgICBhIGRp
cmVjdG9yeSBwcmVzZW50IGluIHRoZSBzdGF0aW9uIGFyY2hpdmUsIGFuZCBvbmUgYWNjb3Vu
dAogICAgICAgICAgICAgICAgIGNvbmZpZ3VyZWQgbm90IHRvIHNlZSBpdC4KCiAgICBOb3Ro
aW5nIHdhcyBkZWxldGVkLiBOb3RoaW5nIHdhcyBjaG1vZGRlZC4gTm90aGluZyB3YXMgbW92
ZWQuIFRoZSBhcmNoaXZlCiAgICB3YXMgbmV2ZXIgdG91Y2hlZC4gV2hhdCB3YXMgdG91Y2hl
ZCB3YXMgYSBnZW5lcmF0ZWQgZmlsZSBpbiBvbmUgYWNjb3VudCdzCiAgICBob21lLCBpbiB0
aGUgb25lIHBsYWNlIG5vYm9keSBkaWZmcywgZG9pbmcgdGhlIG9uZSB0aGluZyB0aGUgc2hl
bGwgd2lsbCBkbwogICAgd2l0aG91dCBjb21tZW50OiBub3Qgc2hvd2luZyB5b3Ugc29tZXRo
aW5nLgoKICAgIFR3byBwZW9wbGUgcmFuIHRoZSBzYW1lIGNvbW1hbmQgaW4gdGhlIHNhbWUg
ZGlyZWN0b3J5IGFuZCBnb3QgZGlmZmVyZW50CiAgICBhbnN3ZXJzLCBhbmQgYm90aCB3ZXJl
IHJpZ2h0LCBhbmQgdGhhdCBpcyBpbiB3cml0aW5nIG5vdy4KCktFU1RSRUx7dGhlX3NoZWxs
X29ubHlfbGllZF90b190aGVfb25lX3dob19vd25lZF9pdH0KCg==
REPORT
EOF
chmod 755 "$LAB/bin/incident-close"

# --- backdating -------------------------------------------------------------
find "$LAB" -exec touch -d '2187-06-28 09:00:00' {} +
touch -d '2186-08-02 11:40:00' "$LAB"/notes/incident.txt "$LAB"/notes/rules.txt "$LAB"/notes/toolchain.txt
touch -d '2187-06-28 06:15:00' "$LAB"/notes/page.txt
# The archive itself has not been touched since the reorganisation it survived.
find "$LAB/archive" -exec touch -d '2186-03-02 08:00:00' {} +
# The account's ordinary files date from when the account was made.
touch -d '2185-09-14 11:00:00' "$LAB"/homes/dorn/.profile "$LAB"/homes/dorn/.bashrc "$LAB"/homes/dorn/.bash_logout
# The generated file says "Generated 2186-03-02" in its own first comment.
# It was last written on a night in 2187, which is the whole point.
touch -d '2187-05-19 02:41:00' "$LAB"/homes/dorn/.config/kestrel/env.sh
